
Output demo.gif

Set Shell "zsh"
Set FontSize 14
Set Width 1200
Set Height 600
Set Padding 20
Set TypingSpeed 50ms
Set Theme catppuccin-mocha
Set WindowBar Colorful


Sleep 500ms
Type "template create https://dl-cdn.alpinelinux.org/alpine/v3.22/releases/cloud/nocloud_alpine-3.22.2-x86_64-bios-cloudinit-r0.qcow2 --vm-id 8000 --storage local-lvm --vm-name alpine
Enter
Sleep 15s
Type "./pdf destroy --vm-id 6666"
Sleep 10s


